import type { Metadata } from 'next'

// These styles apply to every route in the application
import '@/globals.css'
import { ThemeProvider } from "@/components/theme-provider"
import UILayout from '@/components/uiLayout'
import UserProfile from '@/components/user-profile'



export const metadata: Metadata = {
  title: 'knowledge backup',
  description: 'Generated by create next app',
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
          themes={['green', 'zinc', 'dark', 'light', 'system']}
        >
          <UserProfile>
            <UILayout>
              {children}
            </UILayout>
          </UserProfile>
        </ThemeProvider>
      </body >
    </html >
  )
}