import type { Metadata } from "next";

// These styles apply to every route in the application
import "@/globals.css";
import { ThemeProvider } from "@/context/theme-provider";
import UILayout from "@/components/uiLayout";
import WrapUserProfile from "@/components/landing/user-profile";

export const metadata: Metadata = {
  title: "knowledge backup",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
          themes={["green", "zinc", "dark", "light", "system"]}
        >
          <WrapUserProfile>
            <UILayout>{children}</UILayout>
          </WrapUserProfile>
        </ThemeProvider>
      </body>
    </html>
  );
}
